#!/usr/bin/env python

import dask, dask.distributed, dask.array
import logging

logging.getLogger('distributed.comm.tcp').setLevel(logging.ERROR)

cli = dask.distributed.Client(scheduler_file='/tmp/schedfile')
x = dask.array.random.random((2000, 2000), chunks=(10, 10))
y = x.T * x

print(cli.gather(cli.compute(y.sum())))
