#!/bin/bash

if [[ ! -d ~/miniconda2 ]]; then
	wget 'https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh' && \
		bash Miniconda2-latest-Linux-x86_64.sh
    echo 'export PATH=~/miniconda2/bin:$PATH' > ~/miniconda2/env.sh
fi

. ~/miniconda2/env.sh

conda install dask distributed numpy pandas cython scipy chest lz4 python-snappy ipython
cp /usr/lib64/python2.6/site-packages/{htcondor.so,classad.so} \
	~/miniconda2/lib/python2.7/site-packages/

echo "Next, do this somewhere:"
echo 'git clone -b chtc https://github.com/kvpradap/dmagellan'
echo 'cd dmagellan'
echo 'python setup.py build_ext --inplace'
echo 'python setup.py install'
