#!/bin/bash

if [[ ${1-} == "-conda" ]]; then
	echo "launching with conda"
	conda=true
	shift
else
	echo "launching without conda"
	conda=false
fi

if [[ $# -ne 2 ]]; then
	echo "Usage: ${0##*/} [-conda] <threads> <procs>"
	exit 2
fi

threads=$1
procs=$2

set -e

if $conda; then
	. ~/miniconda2/env.sh
else
	. ./pythonenv.sh
fi
mkdir -p ~/_dask_local
dask-scheduler --local-directory ~/_dask_local &
sleep 10
dask-worker --nthreads $threads --nprocs $procs --local-directory ~/_dask_local 127.0.0.1:8786 &

wait