#!/usr/bin/env python

import sys
import h5py
import random


if len(sys.argv) > 1:
    X = Y = int(sys.argv[1])
else:
    X = Y = 500

f = h5py.File('/tmp/test-datafile.hdf5', 'w')
dset = f.create_dataset("default", (X, Y), dtype='int64')
for x in xrange(X):
    for y in xrange(Y):
        dset[x,y] = 1
f.close()
