#!/bin/bash
. ~/usepython
python=python
which ipython &> /dev/null && python=ipython
$python -i -c '
import dask, distributed
from distributed import Client
from distributed.deploy.adaptive import Adaptive
from dask_condor import HTCondorCluster
import logging, os

logging.basicConfig(level=0)
logging.getLogger("distributed.comm.tcp").setLevel(logging.ERROR)
logging.getLogger("distributed.deploy.adaptive").setLevel(logging.WARNING)

worker_tarball="dask_condor_worker_base.SL6.tar.gz"
if not os.path.exists(worker_tarball):
    worker_tarball = "http://research.cs.wisc.edu/~matyas/dask_condor/" + worker_tarball
htc = HTCondorCluster(worker_tarball=worker_tarball)
cli = Client(htc)
print("htc={0}\ncli={1}".format(htc,cli))
print("To create an adaptive, do\n"
      "\tadapt = Adaptive(htc.scheduler, htc, interval=20000)")
'
